### ISSUE TITLE
filter with simple regexp (without flag) seems not working

### ISSUE THREAD

**Issue by ballinette** [kuzzleio/koncorde#6]
with version 1.1.3 (kuzzle 1.x)

If I subscribe to a filter with following format:
```
regexp: {
    message: '^Hello\ '
}
```
I am notified for any messages, even ones which does not match the regexp.

If I subscribe with a flag, with following format, it works as expected:
```
regexp: {
    message: {
      value: '^Hello\ ',
      flags: 'i'
    }
}
```

**Comment by scottinet** [comment]
I reproduced it ( :fearful: )
